### Variables
@baseUrl = http://127.0.0.1:8000/api
@contentType = application/json

### Register - Créer un nouvel utilisateur
POST {{baseUrl}}/auth/register/
Content-Type: {{contentType}}

{
    "username": "nouveauuser",
    "email": "nouveau@test.com",
    "password": "password123",
    "password_confirm": "password123"
}

### JWT - Login (obtenir tokens)
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "nouveauuser",
    "password": "password123"
}

### 1. Lister toutes les tâches (GET)
GET {{baseUrl}}/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc1NzM2OTg2LCJpYXQiOjE3NzU3MzYwODYsImp0aSI6ImRiM2UyN2JmMjgxZjQ5OTg5NGY5OWRiNTRiZDc5YWRlIiwidXNlcl9pZCI6IjMifQ.KwO6SEP2M5WT3bbbUWQFR5Mokv-PcfbxCbtSjPOsIN0

###
POST {{baseUrl}}/tasks/
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc1NzM1ODIwLCJpYXQiOjE3NzU3MzQ5MjAsImp0aSI6IjFhZDZiNzc0M2Q0ODRiOTU4OWMyNGYxNDc3ZmZhZWExIiwidXNlcl9pZCI6IjIifQ.lhvduUeMI5dLnzbCZHPKP4U8VZHecBBHM3vjRSz6tCY

{
    "title": "Ma tâche sécurisée",
    "priority": "high",
    "status": "todo"
}

### Test CORS - Préflight (OPTIONS)
OPTIONS {{baseUrl}}/tasks/
Origin: http://localhost:5173
Access-Control-Request-Method: POST
